# Generated by Django 5.2.5 on 2025-12-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_webhook_2e47a8_idx',
            old_name='webhook_eve_webhook_b7c89e_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_ghl_app_66d061_idx',
            old_name='webhook_eve_ghl_app_4c8a9f_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_process_9ad371_idx',
            old_name='webhook_eve_process_8f2b1d_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_payload_5794ef_idx',
            old_name='webhook_eve_payload_3e7c2a_idx',
        ),
    ]
