# Generated by Django 5.2.5 on 2025-12-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContraceptiveMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
            ],
            options={
                'verbose_name': 'Metodo Anticonceptivo',
                'verbose_name_plural': 'Metodos Anticonceptivos',
                'db_table': 'contraceptive_method',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DIUType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
            ],
            options={
                'verbose_name': 'Tipo de dispositivo intrauterino',
                'verbose_name_plural': 'Tipos de dispositivos intrauterinos',
                'db_table': 'diu_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'db_table': 'document_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Estado de pago',
                'verbose_name_plural': 'Estados de pago',
                'db_table': 'payment_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
                'db_table': 'payment_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PredeterminedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
            ],
            options={
                'verbose_name': 'Precio Predeterminado',
                'verbose_name_plural': 'Precios Predeterminados',
                'db_table': 'predetermined_prices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_date', models.DateField(verbose_name='Fecha del historial')),
                ('testimony', models.BooleanField(default=True, verbose_name='Testimonio')),
                ('private_observation', models.TextField(blank=True, null=True, verbose_name='Observación privada')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Altura')),
                ('initial_weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Peso Inicial')),
                ('last_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Último peso')),
                ('actual_weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Peso actual')),
                ('menstruation', models.BooleanField(default=True, verbose_name='Menstruación')),
                ('gestation', models.BooleanField(default=True, verbose_name='Gestación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('contraceptive_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='histories_configurations.contraceptivemethod', verbose_name='Método anticonceptivo')),
                ('diu_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='histories_configurations.diutype', verbose_name='Tipo de dispositivo intrauterino')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
                'db_table': 'histories',
                'ordering': ['-history_date', '-created_at'],
            },
        ),
    ]
