# Generated by Django 5.2.5 on 2025-12-08 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('histories_configurations', '0002_initial'),
        ('ubi_geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('document_number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Número de documento')),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='photo_pics/', verbose_name='Foto URL')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombres')),
                ('paternal_lastname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido paterno')),
                ('maternal_lastname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido materno')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono')),
                ('user_name', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nombre de usuario')),
                ('password_change', models.BooleanField(blank=True, default=False, null=True, verbose_name='Cambio de contraseña')),
                ('last_session', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Última sesión')),
                ('account_statement', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, null=True, verbose_name='Estado de la cuenta')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verificación del correo')),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Token de recordatorio')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubi_geo.country', verbose_name='País')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='histories_configurations.documenttype')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código')),
                ('verification_type', models.CharField(choices=[('email_verification', 'Verificación de email'), ('email_change', 'Cambio de email'), ('password_change', 'Cambio de contraseña')], default='email_verification', max_length=50, verbose_name='Tipo de verificación')),
                ('target_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email objetivo')),
                ('is_used', models.BooleanField(default=False, verbose_name='¿Usado?')),
                ('expires_at', models.DateTimeField(verbose_name='Expira en')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='Intentos fallidos')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta')),
                ('created_at', models.DateTimeField(verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(verbose_name='Actualizado en')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Código de verificación de usuario',
                'verbose_name_plural': 'Códigos de verificación de usuarios',
                'db_table': 'users_verification_code',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
