# Generated by Django 5.2.5 on 2025-12-08 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ghl_appointment_id', models.CharField(blank=True, db_index=True, help_text='ID de la cita en GoHighLevel', max_length=255, null=True, unique=True)),
                ('ghl_calendar_id', models.CharField(db_index=True, help_text='ID del calendario en GHL', max_length=255)),
                ('title', models.CharField(help_text='Título/motivo de la cita', max_length=255)),
                ('contact_id', models.CharField(db_index=True, help_text='ID del contacto/paciente en GHL', max_length=255)),
                ('assigned_user_id', models.CharField(blank=True, help_text='ID del terapeuta asignado', max_length=255, null=True)),
                ('start_time', models.DateTimeField(db_index=True, help_text='Inicio de la cita (UTC en DB, Lima en UI)')),
                ('end_time', models.DateTimeField(help_text='Fin de la cita (UTC en DB, Lima en UI)')),
                ('status', models.CharField(choices=[('scheduled', 'Programada'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada'), ('no_show', 'No asistió')], db_index=True, default='scheduled', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales de la cita')),
                ('source', models.CharField(choices=[('rv3', 'Reflexo V3'), ('ghl', 'GoHighLevel')], default='rv3', help_text='Origen de la creación', max_length=50)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en formato JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['ghl_appointment_id'], name='citas_ghl_app_d1391b_idx'), models.Index(fields=['ghl_calendar_id', 'start_time'], name='citas_ghl_cal_a27a78_idx'), models.Index(fields=['status', 'start_time'], name='citas_status_9a7680_idx'), models.Index(fields=['contact_id'], name='citas_contact_ffb441_idx')],
            },
        ),
    ]
