# Generated by Django 5.2.5 on 2025-12-08 16:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ghl_location_id', models.CharField(help_text='ID de la ubicación/subcuenta en GHL', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Nombre de la ubicación', max_length=255)),
                ('timezone', models.CharField(default='America/Lima', help_text='Timezone de la ubicación', max_length=100)),
                ('default_calendar_id', models.CharField(blank=True, help_text='ID del calendario por defecto', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Si la sincronización está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Ubicación',
                'verbose_name_plural': 'Configuraciones de Ubicación',
                'db_table': 'location_settings',
            },
        ),
    ]
